chat_window:
  conversion_area_width: 1000
  max_input_area_height: 300
  min_input_area_height: 100
  tree_node_radiu: 7
  tree_node_space: 20
  tree_node_line_width: 2
  float_window_radiu: 4
  float_window_fixed_width: 200
  float_window_fixed_height: 150
window_base:
  background_images: 
  #  - 'C:/Users/chihu/Pictures/Aoi/ev_sy32_0101.png'
  #  - "C:/Users/chihu/Pictures/Aoi/CG_TM01_0101__base.png"
  #  - "C:/Users/chihu/Pictures/Aoi/ev_ya31_0101.png"
  #  - "C:/Users/chihu/Pictures/Aoi/large_ev116b.png"
   - "C:/Users/chihu/Pictures/Aoi/CG_AO03_0201__base.png"
  #  - "C:/Users/chihu/Pictures/Aoi/cg_na01_0101__base.png"
  #  - "C:/Users/chihu/Pictures/Aoi/large_ev401d.png"